config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path('wiki/notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("td_toolkits_v3.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        'materials/',
        include('td_toolkits_v3.materials.urls', namespace='materials')
    ),
    path(
        'products/',
        include('td_toolkits_v3.products.urls', namespace='products')
    ),
    path(
        'opticals/',
        include('td_toolkits_v3.opticals.urls', namespace='opticals')
    ),
    path(
        'reliabilities/',
        include('td_toolkits_v3.reliabilities.urls', namespace='reliabilities')
    ),
    path(
        'autofill/',
        include('td_toolkits_v3.autofill.urls', namespace='autofill')
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

td_toolkits_v3/autofill/urls.py
from django.urls import path
from . import views

app_name = 'autofill'
urlpatterns = [
    path(
        '',
        views.Index.as_view(),
        name='index',
    ),
    path(
        'ras-test/',
        views.RealiabilitySystemTest.as_view(),
        name='ras-test'
    )
]

td_toolkits_v3/opticals/urls.py
from django.urls import path
from . import views

app_name = "opticals"
urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
    path(
        'axo/upload/',
        views.AxoUploadView.as_view(),
        name='axo_upload'
    ),
    path(
        'axo/upload/success/',
        views.AxoUploadSuccessView.as_view(),
        name='axo_upload_success'
    ),
    # path(
    #     'rdl/cell-gap/upload/',
    #     views.RDLCellGapUploadView.as_view(),
    #     name='rdl_cell_gap_upload'
    # ),
    path(
        'rdl/cell-gap-alter/upload/success/',
        views.AlternativeCellGapUploadView.as_view(),
        name='rdl_cell_gap_alter_upload'
    ),
    path(
        'rdl/cell-gap/upload/success/',
        views.RDLCellGapUploadSuccessView.as_view(),
        name='rdl_cell_gap_upload_success'
    ),
    path(
        'toc/opt/upload/',
        views.OptUploadView.as_view(),
        name='toc_opt_log_upload'
    ),
    path(
        'toc/opt/upload/success/',
        views.OptUploadSuccessView.as_view(),
        name='toc_opt_log_upload_success'
    ),
    path(
        'toc/rt/upload/',
        views.ResponseTimeUploadView.as_view(),
        name='toc_rt_log_upload'
    ),
    path(
        'toc/rt/upload/success/',
        views.ResponseTimeUploadSuccessView.as_view(),
        name='toc_rt_log_upload_success'
    ),
    path(
        'ref/list/',
        views.OpticalReferenceListView.as_view(),
        name='ref_list'
    ),
    # path(
    #     'ref/add/',
    #     views.OpticalReferenceCreateView.as_view(),
    #     name='ref_add'
    # ),
    path(
        'ref/add/',
        views.ProductModelTypeCreateView.as_view(),
        name='ref_add'
    ),
    path(
        'ref/<slug:slug>/',
        views.OpticalReferenceDetailView.as_view(),
        name='ref_detail'
    ),
    path(
        'ref/<slug:slug>/update/',
        views.OpticalReferenceUpdateView.as_view(),
        name='ref_update'
    ),
    path(
        'calculate/',
        views.CalculateOpticalView.as_view(),
        name='calculate'
    ),
    path(
        'calculate/check/',
        views.CalculateCheckView.as_view(),
        name='calculate_check'
    ),
    path(
        'calculate/opt/',
        views.OptFittingView.as_view(),
        name='opt_fitting'
    ),
    path(
        'calculate/opt/check/',
        views.OptFittingCheckView.as_view(),
        name='opt_fitting_check'
    ),
    path(
        'calculate/rt/',
        views.RTFittingView.as_view(),
        name='rt_fitting'
    ),
    path(
        'calculate/rt/check/',
        views.RTFittingCheckView.as_view(),
        name='rt_fitting_check'
    ),
    path(
        'search/',
        views.OpticalSearchView.as_view(),
        name='search'
    ),
    path(
        'search/download/',
        views.OpticalSearchResultDownload.as_view(),
        name='search_download'
    ),
    path(
        'search/profile/list/',
        views.OpticalSearchProfileListView.as_view(),
        name='search_profile_list'
    ),
    path(
        'search/profile/add/',
        views.OpticalSearchProfileCreateView.as_view(),
        name='search_profile_add'
    ),
    path(
        'search/profile/<slug:slug>/',
        views.OpticalSearchProfileDetailView.as_view(),
        name='search_profile_detail'
    ),
    path(
        'search/profile/<slug:slug>/update/',
        views.OpticalSearchProfileUpdateView.as_view(),
        name='search_profile_update'
    ),
    path(
        'search/profile/<slug:slug>/copy/',
        views.OpticalSearchProfileCopyView.as_view(),
        name='search_profile_copy'
    ),
    path(
        'data/dump/',
        views.OpticalDataDumpView.as_view(),
        name='data_dump'
    ),
    path(
        'tr2/',
        views.OpticalPhaseTwoView.as_view(),
        name='tr2'
    ),
    path(
        'tr2/success/',
        views.OpticalPhaseTwoSuccessView.as_view(),
        name='tr2_success'
    ),
    path(
        'tr2/advanced-cr/',
        views.AdvancedContrastRatioIndexView.as_view(),
        name='advanced_contrast'
    ),
    path(
        'tr2/advanced-cr/calculate/',
        views.AdvancedContrastRatioView.as_view(),
        name='advanced_contrast_calculation'
    ),
    path(
        'tr2/advanced-cr/success/',
        views.AdvancedContrastRatioSuccessView.as_view(),
        name='advanced_contrast_ratio_success'
    ),
    path(
        'blu/upload/',
        view=views.BackLightUnitUploadView.as_view(),
        name='blu_upload',
    ),
    path(
        'blu/upload/success/',
        view=views.BackLightUnitUploadSuccessView.as_view(),
        name='blu_upload_success',
    ),
]

td_toolkits_v3/users/urls.py
from django.urls import path

from td_toolkits_v3.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

td_toolkits_v3/autofill/models.py
from django.db import models
from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel

class Project(TimeStampedModel):
    name = models.CharField(max_length=255)
    fab = models.ForeignKey(
        to='products.Factory',
        on_delete=models.CASCADE,
    )

td_toolkits_v3/materials/models.py
from django.db import models
from django.urls import reverse

from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel


class Vender(TimeStampedModel):
    name = models.CharField(
        "Name of Vender", max_length=255, unique=True)
    slug = AutoSlugField(
        "Vender Address",
        unique=True, always_update=False, populate_from="name"
    ) # type: ignore

    def __str__(self):
        return self.name


def get_default_vender():
    return Vender.objects.get_or_create(name="INX")[0]

class RefractionIndex(TimeStampedModel):
    wavelength = models.FloatField(
        "Wavelength", help_text="in nm")
    value = models.FloatField(
        "Refraction Index")
    

    def __str__(self):
        return f"{self.value} at {self.wavelength} nm"

    class Meta:
        abstract = True

class OrdinaryRefractionIndex(RefractionIndex):
    lc = models.ForeignKey(
        'LiquidCrystal', 
        on_delete=models.CASCADE,
        related_name="no_exps",
    )

class ExtraordinaryRefractionIndex(RefractionIndex):
    lc = models.ForeignKey(
        'LiquidCrystal', 
        on_delete=models.CASCADE,
        related_name="ne_exps",
    )

class MaterialType(models.TextChoices):
    AAS = 'AAS', 'AAS'
    TN = 'TN', 'TN'

class LiquidCrystal(TimeStampedModel):
    name = models.CharField(
        "Name of Liquid Crystal", 
        max_length=255, unique=True)
    slug = AutoSlugField(
        "LC Address",
        unique=True, always_update=False, populate_from="name"
    ) # type: ignore
    vender = models.ForeignKey(
        Vender,
        default=get_default_vender, on_delete=models.CASCADE)
    designed_cell_gap = models.FloatField(null=True, blank=True)
    t_ni = models.FloatField('Tni(°C)', null=True, blank=True)
    t_cn = models.FloatField('Tcn(°C)', null=True, blank=True)
    flow_viscosity = models.FloatField(
        'ν(mm^2/s)', 
        null=True, blank=True)
    rotational_viscosity = models.FloatField(
        'γ1(mPa*s)', 
        null=True, blank=True)
    n_e = models.FloatField(null=True, blank=True)
    n_o = models.FloatField(null=True, blank=True)
    e_para = models.FloatField('ε_∥', null=True, blank=True)
    e_perp = models.FloatField('ε_⟂', null=True, blank=True)
    k_11 = models.FloatField('K11(pN)', null=True, blank=True)
    k_22 = models.FloatField('K22(pN)', null=True, blank=True)
    k_33 = models.FloatField('K33(pN)', null=True, blank=True)
    density = models.FloatField('d(g/cm^3)', null=True, blank=True)

    material_type = models.CharField(
        choices=MaterialType.choices,
        default=MaterialType.AAS,
        max_length=10
    )

    # Some property extend from others.
    @property
    def delta_n(self):
        if (self.n_e is None) or (self.n_o is None):
            return None
        else:
            return self.n_e - self.n_o

    @property
    def retardation(self): 
        if (self.designed_cell_gap is None) or (self.delta_n is None):
            return None
        else:
            return self.designed_cell_gap * self.delta_n * 1000

    @property
    def delta_e(self):
        if (self.e_para is None) or (self.e_perp is None):
            return None
        else:
            return self.e_para - self.e_perp
    
    @property
    def scatter_index(self):
        """The higher, the brighter at dark state.(lower CR)"""
        if (self.delta_n is None) \
            or (self.k_11 is None) or (self.k_33 is None):
            return None
        
        n_e = self.n_e
        n_o = self.n_o
        if n_e is None or n_o is None:
            return None
        k_11 = self.k_11
        k_22 = self.k_22 if self.k_22 is not None else (k_11/2)
        k_33 = self.k_33
        return (n_e**2 - n_o**2)**2 * 3 / (k_11 + k_22 + k_33)
        
        

    @property
    def response_index(self):
        """The higher, the slower.(no cell gap)"""
        if (self.rotational_viscosity is None) \
            or (self.k_11 is None):
            return None

        k_22 = self.k_22 if self.k_22 is not None else (self.k_11/2)
        return self.rotational_viscosity / k_22
    
    @property
    def vt_index(self):
        """The higher, the higher LC%"""
        if (self.delta_e is None) or (self.k_11 is None):
            return None
        return abs(self.delta_e / self.k_11)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Return absolute URL to the LC Detail page."""
        return reverse(
            'materials:lc_detail', kwargs={"slug": self.slug}
        )

class Polyimide(TimeStampedModel):
    name = models.CharField(
        "Name of Polyimide", 
        max_length=255, unique=True)
    slug = AutoSlugField(
        "LC Address",
        unique=True, always_update=False, populate_from="name"
    ) # type: ignore
    vender = models.ForeignKey(
        Vender,
        default=get_default_vender, on_delete=models.CASCADE)

    material_type = models.CharField(
        choices=MaterialType.choices,
        default=MaterialType.AAS,
        max_length=10
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Return absolute URL to the PI Detail page."""
        return reverse(
            'materials:pi_detail', kwargs={"slug": self.slug}
        )


class Seal(TimeStampedModel):
    name = models.CharField(
        "Name of Seal", 
        max_length=255, unique=True)
    slug = AutoSlugField(   
        "LC Address",
        unique=True, always_update=False, populate_from="name"
    ) # type: ignore
    vender = models.ForeignKey(
        Vender,
        default=get_default_vender, on_delete=models.CASCADE)
    material_type = models.CharField(
        choices=MaterialType.choices,
        default=MaterialType.AAS,
        max_length=10
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Return absolute URL to the Seal Detail page."""
        return reverse(
            'materials:seal_detail', kwargs={"slug": self.slug}
        )

td_toolkits_v3/products/forms.py
from django import forms
from django.core.cache import cache

import pandas as pd

from td_toolkits_v3.materials.models import(
    LiquidCrystal,
    Polyimide,
    Seal
)
from td_toolkits_v3.products.models import Factory

from .models import (
    Project,
    ProductModelType,
    Experiment,
    Condition,
    Sub,
    Chip
)


class ChipsUploadForm(forms.Form):

    chips = forms.FileField(widget=forms.FileInput(
        attrs={'accept': '.xlsx'}))

    fab = forms.ChoiceField(
        choices=[('rdl', 'RDL')],
        initial='rdl'
    )
    
    def save(self):
        print(self.cleaned_data['chips'])
        chip_df = pd.read_excel(self.cleaned_data['chips'], sheet_name='upload')
        save_log = {
            'file_name': [self.cleaned_data['chips'].name],
            'warning': [],
        }
        df = {}
        for row in chip_df.to_dict(orient='records'):
            if not Chip.objects.filter(
                sub__condition__experiment__project__name=str(row['project']),
                sub__condition__experiment__name=str(row['exp id']),
                name=str(row['id'])
            ).exists():
                project = Project.objects.get_or_create(
                    name=str(row['project']))[0]
                product_type = ProductModelType.objects.get_or_create(
                    name=str(row['platform'])
                )[0]
                experiment = Experiment.objects.get_or_create(
                    name=str(row['exp id']),
                    project=project,
                    product_type=product_type,
                )[0]
                condition = Condition.objects.get_or_create(
                    name=str(row['condition']),
                    experiment=experiment
                )[0]
                try:
                    df[row['condition']][0] += 1
                except KeyError:
                    df[row['condition']] = [1]
                sub = Sub.objects.get_or_create(
                    name=f"{str(row['exp id'])}-{str(row['condition'])}",
                    condition=condition
                )[0]
                # TODO: error handling
                lc = LiquidCrystal.objects.get(name=row['LC'])
                pi = Polyimide.objects.get(name=row['PI'])
                seal = Seal.objects.get(name=row['Seal'])
                Chip.objects.create(
                    name=str(row['id']),
                    short_name=str(row['short id']),
                    sub=sub,
                    lc=lc,
                    pi=pi,
                    seal=seal
                )
            else:
                save_log['warning'].append(
                    f"Chip: {row['id']} already exists"
                )
        
        # Save log to cache
        cache.set('save_log', save_log)
        cache.set('df', pd.DataFrame(df))

td_toolkits_v3/autofill/views.py
from django.views.generic import (
    TemplateView,
    FormView,
)
from django.urls import reverse_lazy

from . import forms

class Index(TemplateView):
    template_name: str = 'base.html'


class RealiabilitySystemTest(FormView):
    template_name: str = 'form_generic.html'
    success_url = reverse_lazy('autofill:ras-test')
    form_class = forms.ReliabilityTestForm
    
    def form_valid(self, form: forms.ReliabilityTestForm):
        form.save()
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'RAS Autofill Test'
        return context

td_toolkits_v3/templates/materials/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Materials{% endblock title %}

{% block content %}
<h1>Materials</h1>
<div>
    <ul>
        <li> <a href="{% url 'materials:lc_list' %}">Liquid Crystal</a> </li>
        <li> <a href="{% url 'materials:pi_list' %}">Polyimide</a> </li>
        <li> <a href="{% url 'materials:seal_list' %}">Seal</a> </li>
        <li> <a href="{% url 'materials:upload' %}">Upload</a> </li>
    </ur>
</div>
{% endblock content %}

td_toolkits_v3/templates/materials/liquidcrystal_detail.html
{% extends "base.html" %}


{% block title %}LC: {{ liquidcrystal.name }}{% endblock title %}


{% block content %}
<h2>{{ liquidcrystal.name }}</h2>

<table class='table table-hover text-center table-striped'>
    <thead>
        <tr>
            <th>Item</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Vender</th>
            <td>{{ liquidcrystal.vender.name }}</td>
        </tr>
        <tr>
            <th>Material Type</th>
            <td>{{ liquidcrystal.material_type }}</td>
        </tr>
        <tr>
            <th>Cell Gap(um)</th>
            <td>{{ liquidcrystal.designed_cell_gap|floatformat:1 }}</td>
        </tr>
        <tr>
            <th>T<sub>NI</sub>(°C)</th>
            <td>{{ liquidcrystal.t_ni|floatformat:1 }}</td>
        </tr>
        <tr>
            <th>T<sub>CN</sub>(°C)</th>
            <td>{{ liquidcrystal.t_cn|floatformat:1 }}</td>
        </tr>
        <tr>
            <th>ν(mm<sup>2</sup>/s)</th>
            <td>{{ liquidcrystal.flow_viscosity|floatformat:1 }}</td>
        </tr>
        <tr>
            <th>γ1(mPa·s)</th>
            <td>{{ liquidcrystal.rotational_viscosity|floatformat:1 }}</td>
        </tr>
        <tr>
            <th>n<sub>e</sub></th>
            <td>{{ liquidcrystal.n_e|floatformat:4 }}</td>
        </tr>
        <tr>
            <th>n<sub>o</sub></th>
            <td>{{ liquidcrystal.n_o|floatformat:4 }}</td>
        </tr>
        <tr>
            <th>Δn</th>
            <td>{{ liquidcrystal.delta_n|floatformat:4 }}</td>
        </tr>
        <tr>
            <th>Δnd</th>
            <td>{{ liquidcrystal.retardation|floatformat:0 }}</td>
        </tr>
        <tr>
            <th>ε<sub>∥</sub></th>
            <td>{{ liquidcrystal.e_para|floatformat:2 }}</td>
        </tr>
        <tr>
            <th>ε<sub>⟂</sub></th>
            <td>{{ liquidcrystal.e_perp|floatformat:2 }}</td>
        </tr>
        <tr>
            <th>k<sub>11</sub></th>
            <td>{{ liquidcrystal.k_11|floatformat:2 }}</td>
        </tr>
        <tr>
            <th>k<sub>22</sub></th>
            <td>{{ liquidcrystal.k_22|floatformat:2 }}</td>
        </tr>
        <tr>
            <th>k<sub>33</sub></th>
            <td>{{ liquidcrystal.k_33|floatformat:2 }}</td>
        </tr>
        <tr>
            <th>density(g/cm<sup>3</sup>)</th>
            <td>{{ liquidcrystal.density|floatformat:3 }}</td>
        </tr>
        <tr>
            <th>Scatter Index</th>
            <td>{{ liquidcrystal.scatter_index|floatformat:4 }}</td>
        </tr>
    </tbody>
</table>

<a href="{% url 'materials:lc_update' liquidcrystal.slug %}" class="btn btn-info">Update</a>

{% endblock content %}

td_toolkits_v3/templates/materials/liquidcrystal_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add LC{% endblock title %}

{% block content %}
<h1>Add Liquid Crystal</h1>
<form method="post" action=".">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock content %}

td_toolkits_v3/templates/materials/liquidcrystal_list.html
{% extends 'base.html' %}


{% block title %}Liquid Crystal List{% endblock title %}

{% block content %}
    <h2>Liquid Crystal List</h2>
<ul>
    {% for lc in liquidcrystal_list %}
        <li><a href="{% url 'materials:lc_detail' lc.slug %}">{{ lc.name }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

td_toolkits_v3/templates/materials/materials_upload.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Materials Upload{% endblock title %}

{% block content %}
<h1>Materials Upload</h1>
<a class="btn btn-primary" href="{% url 'materials:upload' %}?download=1">
    Upload Template Download
</a>
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock content %}

td_toolkits_v3/templates/materials/polyimide_detail.html
{% extends "base.html" %}


{% block title %}PI: {{ polyimide.name }}{% endblock title %}


{% block content %}
<h2>{{ polyimide.name }}</h2>
<p>Vender: {{ polyimide.vender.name }}</p>
<tr>
    <th>Material Type</th>
    <td>{{ polyimide.material_type }}</td>
</tr>
<a href="{% url 'materials:pi_update' polyimide.slug %}" 
    class="btn btn-info">
    Update
</a>
{% endblock content %}

td_toolkits_v3/templates/materials/refraction_index_upload_success.html
{% extends 'base.html' %}

{% block title %}{{title}}{% endblock title %}

{% block content %}
<h2>{{title}}</h2>
<div>
{{ table|safe }}
</div>
<a href="{% url 'opticals:advanced_contrast_calculation' %}" class='btn btn-primary'>
    Continue
</a>
{% endblock content %}

td_toolkits_v3/templates/materials/seal_detail.html
{% extends "base.html" %}


{% block title %}Seal: {{ seal.name }}{% endblock title %}


{% block content %}
<h2>{{ seal.name }}</h2>
<p>Vender: {{ seal.vender.name }}</p>
<tr>
    <th>Material Type</th>
    <td>{{ seal.material_type }}</td>
</tr>
<a href="{% url 'materials:seal_update' seal.slug %}" 
    class="btn btn-info">
    Update
</a>
{% endblock content %}

td_toolkits_v3/templates/materials/vender_list.html
{% extends 'base.html' %}


{% block title %}Vender List{% endblock title %}

{% block content %}
    <h2>Vender List</h2>
<ul>
    {% for lc in vender_list %}
        <li><a href="#TODO">{{ lc.name }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}