config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path('wiki/notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("td_toolkits_v3.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        'materials/',
        include('td_toolkits_v3.materials.urls', namespace='materials')
    ),
    path(
        'products/',
        include('td_toolkits_v3.products.urls', namespace='products')
    ),
    path(
        'opticals/',
        include('td_toolkits_v3.opticals.urls', namespace='opticals')
    ),
    path(
        'reliabilities/',
        include('td_toolkits_v3.reliabilities.urls', namespace='reliabilities')
    ),
    path(
        'autofill/',
        include('td_toolkits_v3.autofill.urls', namespace='autofill')
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

td_toolkits_v3/autofill/urls.py
from django.urls import path
from . import views

app_name = 'autofill'
urlpatterns = [
    path(
        '',
        views.Index.as_view(),
        name='index',
    ),
    path(
        'ras-test/',
        views.RealiabilitySystemTest.as_view(),
        name='ras-test'
    )
]

td_toolkits_v3/opticals/urls.py
from django.urls import path
from . import views

app_name = "opticals"
urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
    path(
        'axo/upload/',
        views.AxoUploadView.as_view(),
        name='axo_upload'
    ),
    path(
        'axo/upload/success/',
        views.AxoUploadSuccessView.as_view(),
        name='axo_upload_success'
    ),
    # path(
    #     'rdl/cell-gap/upload/',
    #     views.RDLCellGapUploadView.as_view(),
    #     name='rdl_cell_gap_upload'
    # ),
    path(
        'rdl/cell-gap-alter/upload/success/',
        views.AlternativeCellGapUploadView.as_view(),
        name='rdl_cell_gap_alter_upload'
    ),
    path(
        'rdl/cell-gap/upload/success/',
        views.RDLCellGapUploadSuccessView.as_view(),
        name='rdl_cell_gap_upload_success'
    ),
    path(
        'toc/opt/upload/',
        views.OptUploadView.as_view(),
        name='toc_opt_log_upload'
    ),
    path(
        'toc/opt/upload/success/',
        views.OptUploadSuccessView.as_view(),
        name='toc_opt_log_upload_success'
    ),
    path(
        'toc/rt/upload/',
        views.ResponseTimeUploadView.as_view(),
        name='toc_rt_log_upload'
    ),
    path(
        'toc/rt/upload/success/',
        views.ResponseTimeUploadSuccessView.as_view(),
        name='toc_rt_log_upload_success'
    ),
    path(
        'ref/list/',
        views.OpticalReferenceListView.as_view(),
        name='ref_list'
    ),
    # path(
    #     'ref/add/',
    #     views.OpticalReferenceCreateView.as_view(),
    #     name='ref_add'
    # ),
    path(
        'ref/add/',
        views.ProductModelTypeCreateView.as_view(),
        name='ref_add'
    ),
    path(
        'ref/<slug:slug>/',
        views.OpticalReferenceDetailView.as_view(),
        name='ref_detail'
    ),
    path(
        'ref/<slug:slug>/update/',
        views.OpticalReferenceUpdateView.as_view(),
        name='ref_update'
    ),
    path(
        'calculate/',
        views.CalculateOpticalView.as_view(),
        name='calculate'
    ),
    path(
        'calculate/check/',
        views.CalculateCheckView.as_view(),
        name='calculate_check'
    ),
    path(
        'calculate/opt/',
        views.OptFittingView.as_view(),
        name='opt_fitting'
    ),
    path(
        'calculate/opt/check/',
        views.OptFittingCheckView.as_view(),
        name='opt_fitting_check'
    ),
    path(
        'calculate/rt/',
        views.RTFittingView.as_view(),
        name='rt_fitting'
    ),
    path(
        'calculate/rt/check/',
        views.RTFittingCheckView.as_view(),
        name='rt_fitting_check'
    ),
    path(
        'search/',
        views.OpticalSearchView.as_view(),
        name='search'
    ),
    path(
        'search/download/',
        views.OpticalSearchResultDownload.as_view(),
        name='search_download'
    ),
    path(
        'search/profile/list/',
        views.OpticalSearchProfileListView.as_view(),
        name='search_profile_list'
    ),
    path(
        'search/profile/add/',
        views.OpticalSearchProfileCreateView.as_view(),
        name='search_profile_add'
    ),
    path(
        'search/profile/<slug:slug>/',
        views.OpticalSearchProfileDetailView.as_view(),
        name='search_profile_detail'
    ),
    path(
        'search/profile/<slug:slug>/update/',
        views.OpticalSearchProfileUpdateView.as_view(),
        name='search_profile_update'
    ),
    path(
        'search/profile/<slug:slug>/copy/',
        views.OpticalSearchProfileCopyView.as_view(),
        name='search_profile_copy'
    ),
    path(
        'data/dump/',
        views.OpticalDataDumpView.as_view(),
        name='data_dump'
    ),
    path(
        'tr2/',
        views.OpticalPhaseTwoView.as_view(),
        name='tr2'
    ),
    path(
        'tr2/success/',
        views.OpticalPhaseTwoSuccessView.as_view(),
        name='tr2_success'
    ),
    path(
        'tr2/advanced-cr/',
        views.AdvancedContrastRatioIndexView.as_view(),
        name='advanced_contrast'
    ),
    path(
        'tr2/advanced-cr/calculate/',
        views.AdvancedContrastRatioView.as_view(),
        name='advanced_contrast_calculation'
    ),
    path(
        'tr2/advanced-cr/success/',
        views.AdvancedContrastRatioSuccessView.as_view(),
        name='advanced_contrast_ratio_success'
    ),
    path(
        'blu/upload/',
        view=views.BackLightUnitUploadView.as_view(),
        name='blu_upload',
    ),
    path(
        'blu/upload/success/',
        view=views.BackLightUnitUploadSuccessView.as_view(),
        name='blu_upload_success',
    ),
]

td_toolkits_v3/users/urls.py
from django.urls import path

from td_toolkits_v3.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

td_toolkits_v3/autofill/models.py
from django.db import models
from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel

class Project(TimeStampedModel):
    name = models.CharField(max_length=255)
    fab = models.ForeignKey(
        to='products.Factory',
        on_delete=models.CASCADE,
    )

td_toolkits_v3/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name Do Not Cover Name Patterns
    # Around the Globe.
    name = models.CharField(
        _("Name of User"), blank=True, max_length=255
    )

    def get_absolute_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.username}
        )

td_toolkits_v3/products/forms.py
from django import forms
from django.core.cache import cache

import pandas as pd

from td_toolkits_v3.materials.models import(
    LiquidCrystal,
    Polyimide,
    Seal
)
from td_toolkits_v3.products.models import Factory

from .models import (
    Project,
    ProductModelType,
    Experiment,
    Condition,
    Sub,
    Chip
)


class ChipsUploadForm(forms.Form):

    chips = forms.FileField(widget=forms.FileInput(
        attrs={'accept': '.xlsx'}))

    fab = forms.ChoiceField(
        choices=[('rdl', 'RDL')],
        initial='rdl'
    )
    
    def save(self):
        print(self.cleaned_data['chips'])
        chip_df = pd.read_excel(self.cleaned_data['chips'], sheet_name='upload')
        save_log = {
            'file_name': [self.cleaned_data['chips'].name],
            'warning': [],
        }
        df = {}
        for row in chip_df.to_dict(orient='records'):
            if not Chip.objects.filter(
                sub__condition__experiment__project__name=str(row['project']),
                sub__condition__experiment__name=str(row['exp id']),
                name=str(row['id'])
            ).exists():
                project = Project.objects.get_or_create(
                    name=str(row['project']))[0]
                product_type = ProductModelType.objects.get_or_create(
                    name=str(row['platform'])
                )[0]
                experiment = Experiment.objects.get_or_create(
                    name=str(row['exp id']),
                    project=project,
                    product_type=product_type,
                )[0]
                condition = Condition.objects.get_or_create(
                    name=str(row['condition']),
                    experiment=experiment
                )[0]
                try:
                    df[row['condition']][0] += 1
                except KeyError:
                    df[row['condition']] = [1]
                sub = Sub.objects.get_or_create(
                    name=f"{str(row['exp id'])}-{str(row['condition'])}",
                    condition=condition
                )[0]
                # TODO: error handling
                lc = LiquidCrystal.objects.get(name=row['LC'])
                pi = Polyimide.objects.get(name=row['PI'])
                seal = Seal.objects.get(name=row['Seal'])
                Chip.objects.create(
                    name=str(row['id']),
                    short_name=str(row['short id']),
                    sub=sub,
                    lc=lc,
                    pi=pi,
                    seal=seal
                )
            else:
                save_log['warning'].append(
                    f"Chip: {row['id']} already exists"
                )
        
        # Save log to cache
        cache.set('save_log', save_log)
        cache.set('df', pd.DataFrame(df))

td_toolkits_v3/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {
            "duplicate_username": _(
                "This username has already been taken."
            )
        }
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(
            self.error_messages["duplicate_username"]
        )

td_toolkits_v3/autofill/views.py
from django.views.generic import (
    TemplateView,
    FormView,
)
from django.urls import reverse_lazy

from . import forms

class Index(TemplateView):
    template_name: str = 'base.html'


class RealiabilitySystemTest(FormView):
    template_name: str = 'form_generic.html'
    success_url = reverse_lazy('autofill:ras-test')
    form_class = forms.ReliabilityTestForm
    
    def form_valid(self, form: forms.ReliabilityTestForm):
        form.save()
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'RAS Autofill Test'
        return context

td_toolkits_v3/products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    TemplateView
)
from django.views.generic.edit import FormView
from django.core.cache import cache

import pandas as pd

from .models import (
    Chip,
)
from .forms import ChipsUploadForm

class ChipListView(ListView):
    model = Chip
    paginate_by = 100

class ChipsBatchCreateView(LoginRequiredMixin, FormView):
    template_name = 'form_generic.html'
    form_class = ChipsUploadForm
    success_url = reverse_lazy('products:chip_upload_success')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Chips Upload'
        context['file_path'] = reverse_lazy('materials:template') \
                             + '?download=optical_condition_upload_template'

        return context
    
class ChipBatchCreateSuccessView(TemplateView):
    template_name = 'success_generic.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Chips Upload Success'
        df: pd.DataFrame = cache.get('df')
        context['log'] = cache.get('save_log')
        try:
            context['table'] = df.to_html(
                float_format=lambda x: f'{x:.4f}',
                classes='table table-striped table-bordered table-hover',
                justify='center',
                index=False,
                escape=False,
            )
        except:
            context['table'] = None
        context['nexts'] = {
            "RDL Upload": reverse_lazy('opticals:rdl_cell_gap_alter_upload'),
            "AXO Upload": reverse_lazy('opticals:axo_upload'),
        }
        return context

td_toolkits_v3/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    DetailView,
    RedirectView,
    UpdateView,
)

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These Next Two Lines Tell the View to Index
    #   Lookups by Username
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = [
        "name",
    ]

    # We already imported user in the View code above,
    #   remember?
    model = User

    # Send the User Back to Their Own Page after a
    #   successful Update
    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

    def get_object(self):
        # Only Get the User Record for the
        #   User Making the Request
        return User.objects.get(
            username=self.request.user.username
        )


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )


user_redirect_view = UserRedirectView.as_view()

td_toolkits_v3/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}td_toolkits_v3{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  </head>

  <body>
    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">TD Toolkits V3</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'materials:index' %}">Material</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'opticals:index' %}">Optical</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reliabilities:index' %}">Reliability</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              {% comment %} <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li> {% endcomment %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              {% comment %} <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li> {% endcomment %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
        <div class='mr-sm-2 note'>有問題請恰曾煒翔(550-23477)</div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Tools for TD, reconstruct version 3 This text is inherited on other pages!</p>
        <p>公測中，歡迎隨意使用。</p>
        <P>另外，目前 Debug 模式有打開，如果遇到問題再麻煩把頁面資訊截圖給我。方便 debug。</P>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Select2 -->
      <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
      </script>

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>
 

td_toolkits_v3/templates/form_generic.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<h1>{{ title }}</h1>
{% if file_path %}
<a href="{{ file_path }}" class='btn btn-primary'>
    Template Download
</a>
<hr>
{% endif %}
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% if message %}
<div>
    {{ message }}
</div>
{% endif %}
{% endblock content %}

td_toolkits_v3/templates/formset_generic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<h1>{{ title }}</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_form_errors }}
    {{ form|crispy }}
    {{ formset.non_form_errors }}
    {{ formset.management_form }}
    {% for form in formset %}
    {{ form|crispy }}
    {% endfor %}
    <button type="submit" class="btn btn-primary">
        Save
    </button>
</form>
{% endblock content %}

td_toolkits_v3/templates/list_generic.html
{% extends 'base.html' %}


{% block object_name %}
{{ object_name }} List
{% endblock object_name %}

{% block content %}
<h2>{{ object_name }} List</h2>
<ul>
    {% for obj in object_list %}
        <li><a href="{% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}{{ obj.get_absolute_url }}">
            {{ obj.name }}
        </a></li>
    {% endfor %}
</ul>
{% if add_url %}
<hr>
<p>Do not see the {{ object_name.lower }} on the list? Add new one</p>
<a class='btn btn-primary' href="{{ add_url }}">
   Create New {{ object_name }}
</a>
{% endif %}
{% endblock content %}

td_toolkits_v3/templates/success_generic.html
{% extends 'base.html' %}

{% block title %}{{title}}{% endblock title %};

{% block content %}
<h1>{{title}}</h1>
{% for target, url in nexts.items %}
<a class="btn btn-primary" href={{url}}>{{target}}</a>
{% endfor %}
<hr/>
{% if table %}
<div>
    {{table|safe}}
</div>
{% endif %}
{% if log.file_name %}
<div class="alert alert-info" role="alert">
    <h4 class="alert-heading">File Name</h4>
    {% for row in log.file_name %}
        <p>{{row}}</p>
    {% endfor %}
</div>
{% endif %}

{% if log.warning %}
<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Warning</h4>
    {% for row in log.warning %}
        <p>{{row}}</p>
    {% endfor %}
</div>
{% endif %}

{% endblock content %}

td_toolkits_v3/templates/upload_generic.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<h1>{{ title }}</h1>
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock content %}