config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path('wiki/notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("td_toolkits_v3.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        'materials/',
        include('td_toolkits_v3.materials.urls', namespace='materials')
    ),
    path(
        'products/',
        include('td_toolkits_v3.products.urls', namespace='products')
    ),
    path(
        'opticals/',
        include('td_toolkits_v3.opticals.urls', namespace='opticals')
    ),
    path(
        'reliabilities/',
        include('td_toolkits_v3.reliabilities.urls', namespace='reliabilities')
    ),
    path(
        'autofill/',
        include('td_toolkits_v3.autofill.urls', namespace='autofill')
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

td_toolkits_v3/autofill/urls.py
from django.urls import path
from . import views

app_name = 'autofill'
urlpatterns = [
    path(
        '',
        views.Index.as_view(),
        name='index',
    ),
    path(
        'ras-test/',
        views.RealiabilitySystemTest.as_view(),
        name='ras-test'
    )
]

td_toolkits_v3/opticals/urls.py
from django.urls import path
from . import views

app_name = "opticals"
urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
    path(
        'axo/upload/',
        views.AxoUploadView.as_view(),
        name='axo_upload'
    ),
    path(
        'axo/upload/success/',
        views.AxoUploadSuccessView.as_view(),
        name='axo_upload_success'
    ),
    # path(
    #     'rdl/cell-gap/upload/',
    #     views.RDLCellGapUploadView.as_view(),
    #     name='rdl_cell_gap_upload'
    # ),
    path(
        'rdl/cell-gap-alter/upload/success/',
        views.AlternativeCellGapUploadView.as_view(),
        name='rdl_cell_gap_alter_upload'
    ),
    path(
        'rdl/cell-gap/upload/success/',
        views.RDLCellGapUploadSuccessView.as_view(),
        name='rdl_cell_gap_upload_success'
    ),
    path(
        'toc/opt/upload/',
        views.OptUploadView.as_view(),
        name='toc_opt_log_upload'
    ),
    path(
        'toc/opt/upload/success/',
        views.OptUploadSuccessView.as_view(),
        name='toc_opt_log_upload_success'
    ),
    path(
        'toc/rt/upload/',
        views.ResponseTimeUploadView.as_view(),
        name='toc_rt_log_upload'
    ),
    path(
        'toc/rt/upload/success/',
        views.ResponseTimeUploadSuccessView.as_view(),
        name='toc_rt_log_upload_success'
    ),
    path(
        'ref/list/',
        views.OpticalReferenceListView.as_view(),
        name='ref_list'
    ),
    # path(
    #     'ref/add/',
    #     views.OpticalReferenceCreateView.as_view(),
    #     name='ref_add'
    # ),
    path(
        'ref/add/',
        views.ProductModelTypeCreateView.as_view(),
        name='ref_add'
    ),
    path(
        'ref/<slug:slug>/',
        views.OpticalReferenceDetailView.as_view(),
        name='ref_detail'
    ),
    path(
        'ref/<slug:slug>/update/',
        views.OpticalReferenceUpdateView.as_view(),
        name='ref_update'
    ),
    path(
        'calculate/',
        views.CalculateOpticalView.as_view(),
        name='calculate'
    ),
    path(
        'calculate/check/',
        views.CalculateCheckView.as_view(),
        name='calculate_check'
    ),
    path(
        'calculate/opt/',
        views.OptFittingView.as_view(),
        name='opt_fitting'
    ),
    path(
        'calculate/opt/check/',
        views.OptFittingCheckView.as_view(),
        name='opt_fitting_check'
    ),
    path(
        'calculate/rt/',
        views.RTFittingView.as_view(),
        name='rt_fitting'
    ),
    path(
        'calculate/rt/check/',
        views.RTFittingCheckView.as_view(),
        name='rt_fitting_check'
    ),
    path(
        'search/',
        views.OpticalSearchView.as_view(),
        name='search'
    ),
    path(
        'search/download/',
        views.OpticalSearchResultDownload.as_view(),
        name='search_download'
    ),
    path(
        'search/profile/list/',
        views.OpticalSearchProfileListView.as_view(),
        name='search_profile_list'
    ),
    path(
        'search/profile/add/',
        views.OpticalSearchProfileCreateView.as_view(),
        name='search_profile_add'
    ),
    path(
        'search/profile/<slug:slug>/',
        views.OpticalSearchProfileDetailView.as_view(),
        name='search_profile_detail'
    ),
    path(
        'search/profile/<slug:slug>/update/',
        views.OpticalSearchProfileUpdateView.as_view(),
        name='search_profile_update'
    ),
    path(
        'search/profile/<slug:slug>/copy/',
        views.OpticalSearchProfileCopyView.as_view(),
        name='search_profile_copy'
    ),
    path(
        'data/dump/',
        views.OpticalDataDumpView.as_view(),
        name='data_dump'
    ),
    path(
        'tr2/',
        views.OpticalPhaseTwoView.as_view(),
        name='tr2'
    ),
    path(
        'tr2/success/',
        views.OpticalPhaseTwoSuccessView.as_view(),
        name='tr2_success'
    ),
    path(
        'tr2/advanced-cr/',
        views.AdvancedContrastRatioIndexView.as_view(),
        name='advanced_contrast'
    ),
    path(
        'tr2/advanced-cr/calculate/',
        views.AdvancedContrastRatioView.as_view(),
        name='advanced_contrast_calculation'
    ),
    path(
        'tr2/advanced-cr/success/',
        views.AdvancedContrastRatioSuccessView.as_view(),
        name='advanced_contrast_ratio_success'
    ),
    path(
        'blu/upload/',
        view=views.BackLightUnitUploadView.as_view(),
        name='blu_upload',
    ),
    path(
        'blu/upload/success/',
        view=views.BackLightUnitUploadSuccessView.as_view(),
        name='blu_upload_success',
    ),
]

td_toolkits_v3/users/urls.py
from django.urls import path

from td_toolkits_v3.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

td_toolkits_v3/autofill/models.py
from django.db import models
from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel

class Project(TimeStampedModel):
    name = models.CharField(max_length=255)
    fab = models.ForeignKey(
        to='products.Factory',
        on_delete=models.CASCADE,
    )

td_toolkits_v3/materials/forms.py
from django import forms
from django.core.cache import cache

import pandas as pd

from .models import (
    Vender,
    LiquidCrystal,
    Polyimide,
    Seal,
    OrdinaryRefractionIndex,
    ExtraordinaryRefractionIndex,
)

class MaterialsUploadForm(forms.Form):
    materials = forms.FileField(
        help_text='Excel file(.xlsx)',
        widget=forms.FileInput(attrs={'accept': '.xlsx'})
    )

    def save(self):
        lc_df = pd.read_excel(
            self.cleaned_data['materials'], sheet_name='LiquidCrystal')
        pi_df = pd.read_excel(
            self.cleaned_data['materials'], sheet_name='Polyimide')
        seal_df = pd.read_excel(
            self.cleaned_data['materials'], sheet_name='Seal')
        save_log = {
            'file_name': [self.cleaned_data['materials'].name],
            'warning': [],
        }
        df_log = {
            'material': [],
            'name': [],
        }
        # LC part
        for row in lc_df.to_dict(orient='records'):
            if LiquidCrystal.objects.filter(name=row['Name']):
                save_log['warning'].append(
                    f"LC: {row['Name']} already exists"
                )
                continue
            else:
                vender = Vender.objects.get_or_create(
                    name=str(row['Vender']))[0]
                LiquidCrystal.objects.create(
                    name=str(row['Name']),
                    vender=vender,
                    designed_cell_gap=float(row['designed cell gap(um)']),
                    t_ni=float(row['Tni(°C)']),
                    t_cn=float(row['Tcn(°C)']),
                    flow_viscosity=float(row['Flow Viscosity(ν)(mm^2/s)']),
                    rotational_viscosity=float(row['Rotational Viscosity(γ1)(mPa*s)']),
                    n_e=float(row['n_e']),
                    n_o=float(row['n_o']),
                    e_para=float(row['ε_∥']),
                    e_perp=float(row['ε_⟂']),
                    k_11=float(row['K11(pN)']),
                    k_22=float(row['K22(pN)']),
                    k_33=float(row['K33(pN)']),
                    density=float(row['d(g/cm^3)']),
                )
                df_log['material'].append('LC')
                df_log['name'].append(row['Name'])

        # PI part
        for row in pi_df.to_dict(orient='records'):
            if Polyimide.objects.filter(name=row['Name']):
                save_log['warning'].append(
                    f"PI: {row['Name']} already exists"
                )
                continue
            else:
                vender = Vender.objects.get_or_create(
                    name=str(row['Vender']))[0]
                Polyimide.objects.create(
                    name=str(row['Name']),
                    vender=vender,
                )
                df_log['material'].append('PI')
                df_log['name'].append(row['Name'])
        # Seal part
        for row in seal_df.to_dict(orient='records'):
            if Seal.objects.filter(name=row['Name']):
                save_log['warning'].append(
                    f"Seal: {row['Name']} already exists"
                )
                continue
            else:
                vender = Vender.objects.get_or_create(
                    name=str(row['Vender']))[0]
                Seal.objects.create(
                    name=str(row['Name']),
                    vender=vender,
                )
                df_log['material'].append('Seal')
                df_log['name'].append(row['Name'])
        # Save log to cache
        cache.set('save_log', save_log)
        cache.set('df_log', pd.DataFrame(df_log))
        

class MaterialsUpdateForm(forms.Form):
    materials = forms.FileField(
        help_text='Excel file(.xlsx)',
        widget=forms.FileInput(attrs={'accept': '.xlsx'})
    )

    def save(self):
        lc_df = pd.read_excel(
            self.cleaned_data['materials'], sheet_name='LiquidCrystal')
        pi_df = pd.read_excel(
            self.cleaned_data['materials'], sheet_name='Polyimide')
        seal_df = pd.read_excel(
            self.cleaned_data['materials'], sheet_name='Seal')
        # LC part
        for row in lc_df.to_dict(orient='records'):
            try:
                lc = LiquidCrystal.objects.get(name=row['Name'])
                vender = Vender.objects.get_or_create(
                    name=str(row['Vender']))[0]
                
                lc.vender=vender
                lc.designed_cell_gap=float(row['designed cell gap(um)'])
                lc.t_ni=float(row['Tni(°C)'])
                lc.t_cn=float(row['Tcn(°C)'])
                lc.flow_viscosity=float(row['Flow Viscosity(ν)(mm^2/s)'])
                lc.rotational_viscosity=float(row['Rotational Viscosity(γ1)(mPa*s)'])
                lc.n_e=float(row['n_e'])
                lc.n_o=float(row['n_o'])
                lc.e_para=float(row['ε_∥'])
                lc.e_perp=float(row['ε_⟂'])
                lc.k_11=float(row['K11(pN)'])
                lc.k_22=float(row['K22(pN)'])
                lc.k_33=float(row['K33(pN)'])
                lc.density=float(row['d(g/cm^3)'])

                lc.save()
                
            except Exception as e: print(e)

        # PI part
        for row in pi_df.to_dict(orient='records'):
            try:
                pi = Polyimide.objects.get(name=row['Name'])
                vender = Vender.objects.get_or_create(
                    name=str(row['Vender']))[0]
                
                pi.name=str(row['Name'])
                pi.vender=vender

                pi.save()
                
            except Exception as e: print(e)

        # Seal part
        for row in seal_df.to_dict(orient='records'):
            try:
                seal = Seal.objects.get(name=row['Name'])
                vender = Vender.objects.get_or_create(
                    name=str(row['Vender']))[0]
                
                seal.name=str(row['Name'])
                seal.vender=vender

                seal.save()
                
            except Exception as e: print(e)

class RefractionIndexUploadForm(forms.Form):
    refraction_index = forms.FileField(
        widget=forms.FileInput(attrs={"accept": ".xlsx"})
    )
    
    def save(self):
        df = pd.read_excel(
            self.cleaned_data['refraction_index'],
            sheet_name='upload'
        )
        lcs = []
        for row in df.to_dict(orient='records'):
            try:
                lc = LiquidCrystal.objects.get(name=row['LC'])
                if lc.ne_exps.all():
                    continue
                no_logs = [
                    OrdinaryRefractionIndex(
                        wavelength=450,
                        value=float(row['no_450']),
                        lc=lc,
                    ),
                    OrdinaryRefractionIndex(
                        wavelength=509,
                        value=float(row['no_509']),
                        lc=lc,
                    ),
                    OrdinaryRefractionIndex(
                        wavelength=546,
                        value=float(row['no_546']),
                        lc=lc,
                    ),
                    OrdinaryRefractionIndex(
                        wavelength=589,
                        value=float(row['no_589']),
                        lc=lc,
                    ),
                    OrdinaryRefractionIndex(
                        wavelength=633,
                        value=float(row['no_633']),
                        lc=lc,
                    ),
                ]
                ne_logs = [
                    ExtraordinaryRefractionIndex(
                        wavelength=450,
                        value=float(row['ne_450']),
                        lc=lc,
                    ),
                    ExtraordinaryRefractionIndex(
                        wavelength=509,
                        value=float(row['ne_509']),
                        lc=lc,
                    ),
                    ExtraordinaryRefractionIndex(
                        wavelength=546,
                        value=float(row['ne_546']),
                        lc=lc,
                    ),
                    ExtraordinaryRefractionIndex(
                        wavelength=589,
                        value=float(row['ne_589']),
                        lc=lc,
                    ),
                    ExtraordinaryRefractionIndex(
                        wavelength=633,
                        value=float(row['ne_633']),
                        lc=lc,
                    ),
                ]
                OrdinaryRefractionIndex.objects.bulk_create(no_logs)
                ExtraordinaryRefractionIndex.objects.bulk_create(ne_logs)
                
            except LiquidCrystal.DoesNotExist:
                continue
            
            lcs.append(lc)
        cache.set('lcs', lcs, 30)

td_toolkits_v3/autofill/views.py
from django.views.generic import (
    TemplateView,
    FormView,
)
from django.urls import reverse_lazy

from . import forms

class Index(TemplateView):
    template_name: str = 'base.html'


class RealiabilitySystemTest(FormView):
    template_name: str = 'form_generic.html'
    success_url = reverse_lazy('autofill:ras-test')
    form_class = forms.ReliabilityTestForm
    
    def form_valid(self, form: forms.ReliabilityTestForm):
        form.save()
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'RAS Autofill Test'
        return context

td_toolkits_v3/templates/reliabilities/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Reliabilities{% endblock title %}

{% block content %}
<h1>Reliabilities</h1>
<a href="{% url 'reliabilities:search' %}?pure=1&profile=default" 
    class='btn btn-primary'>
    RA Search
</a>
<hr>
<h2>Management</h2>
<a class='btn btn-info' href='/wiki/reliability-user-guide' target="_blank">User Guide</a>
<ol>
    <li> <a href="{% url 'reliabilities:upload' %}">Supplier RA data upload</a> </li>
    <li> <a href="{% url 'reliabilities:search_profile_list' %}">RA Search Profile</a> </li>
    <li> <a href="{% url 'reliabilities:ushape' %}">U Shape</a></li>
</ol>
<hr>
<h2>TR 2</h2>
<ol>
    <li> <a href="{% url 'reliabilities:tr2' %}">TR2 work</a> </li>
</ol>
<h2>TR 3</h2>
<ol>
    <li> <a href="{% url 'reliabilities:image_sticking_traffic_light' %}">IS Traffic Light</a> </li>
{% endblock content %}

td_toolkits_v3/templates/reliabilities/reliabilitysearchprofile_detail.html
{% extends "base.html" %}
{% block title %}
Optical Search Profile: {{ reliabilitysearchprofile }}
{% endblock title %}
{% block content %}
<h2>Optical Search Profile: {{ reliabilitysearchprofile }}</h2>
<div class='table'>
<table class='table table-hover text-center table-striped'>
    <thead>
        <tr>
            <th>Item</th>
            <th>Value</th>
            <th>Weight</th>
            <th>Vender</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Material Type</th>
            <td>{{ reliabilitysearchprofile.material_type }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>VHR</th>
            <td>{{ reliabilitysearchprofile.voltage_holding_ratio }}</td>
            <td>{{ reliabilitysearchprofile.voltage_holding_ratio_weight }}</td>
            <td>
                {% for vender in reliabilitysearchprofile.voltage_holding_ratio_venders.values %}
                {{ vender.name }}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Δ angle</th>
            <td>{{ reliabilitysearchprofile.delta_angle }}</td>
            <td>{{ reliabilitysearchprofile.delta_angle_weight }}</td>
            <td>
                {% for vender in reliabilitysearchprofile.delta_angle_venders.values %}
                {{ vender.name }}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Adhesion</th>
            <td>{{ reliabilitysearchprofile.adhesion }}</td>
            <td>{{ reliabilitysearchprofile.adhesion_weight }}</td>
            <td>
                {% for vender in reliabilitysearchprofile.adhesion_venders.values %}
                {{ vender.name }}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>LTS</th>
            <td>{{ reliabilitysearchprofile.low_temperature_storage }}</td>
            <td>{{ reliabilitysearchprofile.low_temperature_storage_weight }}</td>
            <td>
                {% for vender in reliabilitysearchprofile.low_temperature_storage_venders.values %}
                {{ vender.name }}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>PCT</th>
            <td>{{ reliabilitysearchprofile.pressure_cooking_test }}</td>
            <td>{{ reliabilitysearchprofile.pressure_cooking_test_weight }}</td>
            <td>
                {% for vender in reliabilitysearchprofile.pressure_cooking_test_venders.values %}
                {{ vender.name }}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Seal WVTR</th>
            <td>{{ reliabilitysearchprofile.seal_wvtr }}</td>
            <td>{{ reliabilitysearchprofile.seal_wvtr_weight }}</td>
            <td>
                {% for vender in reliabilitysearchprofile.seal_wvtr_venders.values %}
                {{ vender.name }}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>U-Shape AC</th>
            <td>{{ reliabilitysearchprofile.u_shape_ac }}</td>
            <td>{{ reliabilitysearchprofile.u_shape_ac_weight }}</td>
            <td>
                {% for vender in reliabilitysearchprofile.u_shape_ac_venders.values %}
                {{ vender.name }}
                {% endfor %}
            </td>
        </tr>
    </tbody>
</table>
</div>
<a href="{% url 'reliabilities:search_profile_update' reliabilitysearchprofile.slug %}"
    class='btn btn-info'
>
    Update
</a>
{% endblock content %}

td_toolkits_v3/templates/reliabilities/reliabilitysearchprofile_list.html
{% extends "base.html" %}

{% block title %}RA Search Profile List{% endblock title %}

{% block content %}
<h2>RA Search Profile List</h2>
<ul>
    {% for obj in reliabilitysearchprofile_list %}
    <li><a href="{% url 'reliabilities:search_profile_detail' obj.slug %}">
        {{ obj }}
    </a>
    </li>
    {% endfor %}
</ul>
<hr/>
<p>Add more profile if you like.</p>
<p>
<a class="btn btn-primary"
href="{% url 'reliabilities:search_profile_add' %}" role="button">
Add Profile
</a>
</p>
{% endblock content %}

td_toolkits_v3/templates/reliabilities/search.html
{% extends "base.html" %}
{% block title %}
Reliability Search
{% endblock title %}
{% block content %}
<h2>Reliability Search</h2>
<form action='' method='GET'>
    <h3>Select Configurations</h3>
    <select class='form-select' multiple name='lc_list'>
        {% if q_opt %}
        {% for lc in lc_list %}
        <option selected> {{ lc }}</option>
        {% endfor %}
        {% else %}
        <option selected>ALL</option>
        {% for lc in lc_list %}
        <option> {{ lc }}</option>
        {% endfor %}
        {% endif %}
    </select>
    <select class='form-select' multiple name='pi_list'>
        <option selected>ALL</option>
        {% for pi in pi_list %}
        <option> {{ pi }}</option>
        {% endfor %}
    </select>
    <select class='form-select' multiple name='seal_list'>
        <option selected>ALL</option>
        {% for seal in seal_list %}
        <option> {{ seal }}</option>
        {% endfor %}
    </select>

    <h3>
        <a href="{% url 'reliabilities:search_profile_list' %}"
            data-toggle="tooltip" data-placement="top" 
            title="Set the constraint of search result"
        >
            Search Profile
        </a>
    </h3>
    <select class='from-select' name='profile'>
        {% for obj in profile_list %}
        <option 
        {% if obj.slug == profile.slug %}
        selected
        {% endif %}
        value={{ obj.slug }}
        >
            {{ obj.name }}
        </option>
        {% endfor %}
    </select>
    <button class='btn btn-primary' type='submit'
        data-toggle="tooltip" data-placement="top" 
        title="Change the Search Profile from list"
    >
        Change
    </button>
    <a href="{% url 'reliabilities:search_profile_update' profile.slug %}?next={{request.get_full_path}}"
        class='btn btn-info'
        data-toggle="tooltip" data-placement="top" 
        title="Update the current Search Profile"
    >
        Update
    </a>
    <a href="{% url 'reliabilities:search_profile_copy' profile.slug %}?next={{request.get_full_path}}"
        class='btn btn-info'
        data-toggle="tooltip" data-placement="top" 
        title="Copy the current Search Profile to a new one"
    >
        Copy
    </a>
    <div class='mt-1'>
        <table class='table table-hover text-center table-striped'>
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Value</th>
                    <th>Weight</th>
                    <th>Vender</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>Material Type</th>
                    <td>{{ profile.material_type }}</td>
                    <td></td>
                    <td></td>
                <tr>
                    <th>VHR(%) min</th>
                    <td>{{ profile.voltage_holding_ratio }}</td>
                    <td>{{ profile.voltage_holding_ratio_weight }}</td>
                    <td>
                        {% for vender in profile.voltage_holding_ratio_venders.values %}
                        {{ vender.name }}
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Δ angle(°) max</th>
                    <td>{{ profile.delta_angle }}</td>
                    <td>{{ profile.delta_angle_weight }}</td>
                    <td>
                        {% for vender in profile.delta_angle_venders.values %}
                        {{ vender.name }}
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Adhesion(kgw) min</th>
                    <td>{{ profile.adhesion }}</td>
                    <td>{{ profile.adhesion_weight }}</td>
                    <td>
                        {% for vender in profile.adhesion_venders.values %}
                        {{ vender.name }}
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>LTS(days) min</th>
                    <td>{{ profile.low_temperature_storage }}</td>
                    <td>{{ profile.low_temperature_storage_weight }}</td>
                    <td>
                        {% for vender in profile.low_temperature_storage_venders.values %}
                        {{ vender.name }}
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>PCT(hours) min</th>
                    <td>{{ profile.pressure_cooking_test }}</td>
                    <td>{{ profile.pressure_cooking_test_weight }}</td>
                    <td>
                        {% for vender in profile.pressure_cooking_test_venders.values %}
                        {{ vender.name }}
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Seal WVTR(%) max</th>
                    <td>{{ profile.seal_wvtr }}</td>
                    <td>{{ profile.seal_wvtr_weight }}</td>
                    <td>
                        {% for vender in profile.seal_wvtr_venders.values %}
                        {{ vender.name }}
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>U-Shape AC(%) max</th>
                    <td>{{ profile.u_shape_ac }}</td>
                    <td>{{ profile.u_shape_ac_weight }}</td>
                    <td>
                        {% for vender in profile.u_shape_ac_venders.values %}
                        {{ vender.name }}
                        {% endfor %}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <button class='btn btn-primary' type='submit'>Search</button>
</form>
{% if q %}
<hr>
<h2>Result</h2>
<div>
    <h3>Figure 1: RA Score Histagram</h3>
    {{ ra_plot|safe }}
</div>
<div>
    <h3>Table 1: RA Score</h3>
    {{ ra_score|safe }}
</div>
<div>
    <h3>Table 2: RA Score Raw</h3>
    {{ ra_score_raw|safe }}
</div>
{% if q_opt %}
<a class='btn btn-primary' href="{% url 'opticals:search_download' %}">
    Opt Download
</a>
{% endif %}
<a class='btn btn-primary' href="{% url 'reliabilities:search_download' %}">
    RA Download
</a>
{% endif %}
{% endblock content %}

td_toolkits_v3/templates/reliabilities/tr2_success.html
{% extends "base.html" %}
{% block title %}
TR2 Result
{% endblock title %}
{% block content %}
<h2>TR2 Result</h2>

<div>
    <h3>Figure 1: RA Score Histagram</h3>
    {{ plot|safe }}
</div>
<div>
    <h3>Table 1: RA Score</h3>
    {{ score|safe }}
</div>
<div>
    <h3>Table 2: RA Score Raw</h3>
    {{ summary|safe }}
</div>
{% endblock content %}

td_toolkits_v3/templates/reliabilities/ushape.html
{% extends 'base.html' %}
{% block title %}UShape{% endblock title %}
{% block content %}
<h1>U Shape</h1>
<h2>Voltage Calculate</h2>
<form action='.' method='GET'>
    <h3>Select Data</h3>
    <select class='form-select' name='experiment'>
        {% for exp in experiments %}
        <option>{{ exp }}</option>
        {% endfor %}
    </select>
    <button class='btn btn-primary' type="submit">Submit</button>
</form>
{% if q %}
<h2>Result</h2>
<div>
    <h3>V T curve</h3>
    {{plot|safe}}
</div>
<a href="{% url 'reliabilities:ushape' %}?download=1"
    class='btn btn-primary'
>Download</a>
{% endif %}
{% endblock content %}