config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path('wiki/notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("td_toolkits_v3.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        'materials/',
        include('td_toolkits_v3.materials.urls', namespace='materials')
    ),
    path(
        'products/',
        include('td_toolkits_v3.products.urls', namespace='products')
    ),
    path(
        'opticals/',
        include('td_toolkits_v3.opticals.urls', namespace='opticals')
    ),
    path(
        'reliabilities/',
        include('td_toolkits_v3.reliabilities.urls', namespace='reliabilities')
    ),
    path(
        'autofill/',
        include('td_toolkits_v3.autofill.urls', namespace='autofill')
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

td_toolkits_v3/autofill/urls.py
from django.urls import path
from . import views

app_name = 'autofill'
urlpatterns = [
    path(
        '',
        views.Index.as_view(),
        name='index',
    ),
    path(
        'ras-test/',
        views.RealiabilitySystemTest.as_view(),
        name='ras-test'
    )
]

td_toolkits_v3/opticals/urls.py
from django.urls import path
from . import views

app_name = "opticals"
urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
    path(
        'axo/upload/',
        views.AxoUploadView.as_view(),
        name='axo_upload'
    ),
    path(
        'axo/upload/success/',
        views.AxoUploadSuccessView.as_view(),
        name='axo_upload_success'
    ),
    # path(
    #     'rdl/cell-gap/upload/',
    #     views.RDLCellGapUploadView.as_view(),
    #     name='rdl_cell_gap_upload'
    # ),
    path(
        'rdl/cell-gap-alter/upload/success/',
        views.AlternativeCellGapUploadView.as_view(),
        name='rdl_cell_gap_alter_upload'
    ),
    path(
        'rdl/cell-gap/upload/success/',
        views.RDLCellGapUploadSuccessView.as_view(),
        name='rdl_cell_gap_upload_success'
    ),
    path(
        'toc/opt/upload/',
        views.OptUploadView.as_view(),
        name='toc_opt_log_upload'
    ),
    path(
        'toc/opt/upload/success/',
        views.OptUploadSuccessView.as_view(),
        name='toc_opt_log_upload_success'
    ),
    path(
        'toc/rt/upload/',
        views.ResponseTimeUploadView.as_view(),
        name='toc_rt_log_upload'
    ),
    path(
        'toc/rt/upload/success/',
        views.ResponseTimeUploadSuccessView.as_view(),
        name='toc_rt_log_upload_success'
    ),
    path(
        'ref/list/',
        views.OpticalReferenceListView.as_view(),
        name='ref_list'
    ),
    # path(
    #     'ref/add/',
    #     views.OpticalReferenceCreateView.as_view(),
    #     name='ref_add'
    # ),
    path(
        'ref/add/',
        views.ProductModelTypeCreateView.as_view(),
        name='ref_add'
    ),
    path(
        'ref/<slug:slug>/',
        views.OpticalReferenceDetailView.as_view(),
        name='ref_detail'
    ),
    path(
        'ref/<slug:slug>/update/',
        views.OpticalReferenceUpdateView.as_view(),
        name='ref_update'
    ),
    path(
        'calculate/',
        views.CalculateOpticalView.as_view(),
        name='calculate'
    ),
    path(
        'calculate/check/',
        views.CalculateCheckView.as_view(),
        name='calculate_check'
    ),
    path(
        'calculate/opt/',
        views.OptFittingView.as_view(),
        name='opt_fitting'
    ),
    path(
        'calculate/opt/check/',
        views.OptFittingCheckView.as_view(),
        name='opt_fitting_check'
    ),
    path(
        'calculate/rt/',
        views.RTFittingView.as_view(),
        name='rt_fitting'
    ),
    path(
        'calculate/rt/check/',
        views.RTFittingCheckView.as_view(),
        name='rt_fitting_check'
    ),
    path(
        'search/',
        views.OpticalSearchView.as_view(),
        name='search'
    ),
    path(
        'search/download/',
        views.OpticalSearchResultDownload.as_view(),
        name='search_download'
    ),
    path(
        'search/profile/list/',
        views.OpticalSearchProfileListView.as_view(),
        name='search_profile_list'
    ),
    path(
        'search/profile/add/',
        views.OpticalSearchProfileCreateView.as_view(),
        name='search_profile_add'
    ),
    path(
        'search/profile/<slug:slug>/',
        views.OpticalSearchProfileDetailView.as_view(),
        name='search_profile_detail'
    ),
    path(
        'search/profile/<slug:slug>/update/',
        views.OpticalSearchProfileUpdateView.as_view(),
        name='search_profile_update'
    ),
    path(
        'search/profile/<slug:slug>/copy/',
        views.OpticalSearchProfileCopyView.as_view(),
        name='search_profile_copy'
    ),
    path(
        'data/dump/',
        views.OpticalDataDumpView.as_view(),
        name='data_dump'
    ),
    path(
        'tr2/',
        views.OpticalPhaseTwoView.as_view(),
        name='tr2'
    ),
    path(
        'tr2/success/',
        views.OpticalPhaseTwoSuccessView.as_view(),
        name='tr2_success'
    ),
    path(
        'tr2/advanced-cr/',
        views.AdvancedContrastRatioIndexView.as_view(),
        name='advanced_contrast'
    ),
    path(
        'tr2/advanced-cr/calculate/',
        views.AdvancedContrastRatioView.as_view(),
        name='advanced_contrast_calculation'
    ),
    path(
        'tr2/advanced-cr/success/',
        views.AdvancedContrastRatioSuccessView.as_view(),
        name='advanced_contrast_ratio_success'
    ),
    path(
        'blu/upload/',
        view=views.BackLightUnitUploadView.as_view(),
        name='blu_upload',
    ),
    path(
        'blu/upload/success/',
        view=views.BackLightUnitUploadSuccessView.as_view(),
        name='blu_upload_success',
    ),
]

td_toolkits_v3/users/urls.py
from django.urls import path

from td_toolkits_v3.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

td_toolkits_v3/opticals/models.py
from django.db import models
from django.urls import reverse

from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel
from picklefield.fields import PickledObjectField

import td_toolkits_v3.materials.models as Material

class Instrument(TimeStampedModel):
    name = models.CharField("Instrument Name", max_length=255)
    slug = AutoSlugField(
        "Instrument Address", unique=True, always_update=False, populate_from="name"
    ) # type: ignore
    desc = models.TextField("description", blank=True)
    factory = models.ForeignKey(
        "products.Factory",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    @classmethod
    def default(cls, name, factory):
        return cls.objects.get_or_create(
            name=name,
            factory=factory,
        )[0]

    def __str__(self):
        return f"{self.name} (@{self.factory.name})" # type: ignore


class AxometricsLog(TimeStampedModel):
    chip = models.ForeignKey("products.Chip", on_delete=models.CASCADE)
    measure_point = models.SmallIntegerField()
    x_coord = models.FloatField()
    y_coord = models.FloatField()
    cell_gap = models.FloatField()
    top_rubbing_direct = models.FloatField()
    twist = models.FloatField()
    top_pretilt = models.FloatField()
    bottom_pretilt = models.FloatField()
    rms = models.FloatField()
    iteration = models.FloatField()
    instrument = models.ForeignKey(
        Instrument, on_delete=models.CASCADE, null=True, blank=True
    )

    def __str__(self):
        return (
            f"{self.chip.name}, p {self.measure_point}" + f", cell gap: {self.cell_gap}"
        )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["chip", "measure_point"], name="axo_chip_measure_point"
            )
        ]


class RDLCellGap(TimeStampedModel):
    # One to One relation can not duplicate.
    chip = models.OneToOneField(
        "products.Chip", on_delete=models.CASCADE, related_name="rdl_cell_gap"
    )
    cell_gap = models.FloatField()
    instrument = models.ForeignKey(
        Instrument, on_delete=models.CASCADE, null=True, blank=True
    )

    def __str__(self):
        return self.chip.name

class AlterRdlCellGap(TimeStampedModel):
    chip = models.ForeignKey('products.Chip', on_delete=models.CASCADE)
    measure_point = models.SmallIntegerField()
    cell_gap = models.FloatField()

class OpticalLog(TimeStampedModel):
    chip = models.ForeignKey("products.Chip", on_delete=models.CASCADE)
    measure_point = models.SmallIntegerField()
    measure_time = models.DateTimeField()
    instrument = models.ForeignKey(
        Instrument, on_delete=models.CASCADE, null=True, blank=True
    )
    operator = models.CharField(max_length=255)
    voltage = models.FloatField("Vop")
    lc_percent = models.FloatField()
    w_x = models.FloatField()
    w_y = models.FloatField()
    w_capital_y = models.FloatField("WY")

    @property
    def t_percent(self):
        max_lc_percent = max(
            self.objects.filter( # type: ignore
                chip=self.chip, measure_point=self.measure_point
            ).values_list("lc_percent")
        )[0] 
        return self.lc_percent / max_lc_percent * 100

    def __str__(self):
        return (
            f"{self.chip.name}, p {self.measure_point} "
            + f"v: {self.voltage}, ({self.lc_percent},"
            + f"{self.w_x}, {self.w_y}, {self.w_capital_y})"
        )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["chip", "measure_point", "voltage"], name="opt_unique"
            )
        ]


class ResponseTimeLog(TimeStampedModel):
    chip = models.ForeignKey("products.Chip", on_delete=models.CASCADE)
    measure_point = models.SmallIntegerField("Point")
    measure_time = models.DateTimeField()
    instrument = models.ForeignKey(
        Instrument, on_delete=models.CASCADE, null=True, blank=True
    )
    operator = models.CharField(max_length=255)
    voltage = models.FloatField("Vop")
    time_rise = models.FloatField("Tr")
    time_fall = models.FloatField("Tf")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["chip", "measure_point", "voltage"], name="rt_unique"
            )
        ]


class OpticalReference(TimeStampedModel):
    """
    Cause **Reference** should be mass product.
    There would be only one optical reference for each product model type.
    """

    product_model_type = models.OneToOneField(
        "products.ProductModelType",
        on_delete=models.CASCADE,
        verbose_name="Product Name",
    )

    def slug_gen(obj): # type: ignore
        product = obj.product_model_type.name
        factory = obj.product_model_type.factory.name
        return f"{product}-{factory}"

    slug = AutoSlugField(
        "opt ref addr", unique=True, always_update=False, 
        # # This is the django-extension parameters 
        # populate_from=[
        #     'product_model_type__name',
        #     'product_model_type__factory__name'
        # ]
        populate_from=slug_gen
    ) # type: ignore

    lc: Material.LiquidCrystal = models.ForeignKey(
        "materials.LiquidCrystal",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="LC",
    ) # type: ignore
    pi: Material.Polyimide = models.ForeignKey(
        "materials.Polyimide",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="PI",
    ) # type: ignore
    seal: Material.Seal = models.ForeignKey(
        "materials.Seal",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="Seal",
    ) # type: ignore

    cell_gap = models.FloatField("Cell Gap(um)")
    voltage = models.FloatField(default=5.0)
    ito_slit = models.FloatField("ITO Slit(°)", null=True, blank=True)

    class TFTTech(models.TextChoices):
        AMORPHOUS = "a_Si", "a-Si"
        LTPS = "LTPS", "LTPS"

        __empty__ = "Unknown"

    tft_tech = models.CharField(
        "TFT Tech", choices=TFTTech.choices, max_length=20)
    transmittance = models.FloatField("T%")
    time_rise = models.FloatField("Tr(ms)")
    time_fall = models.FloatField("Tf(ms)")
    gray_to_gray = models.FloatField("G2G(ms)")
    w_x = models.FloatField("Wx")
    w_y = models.FloatField("Wy")
    contrast_ratio = models.FloatField("CR")

    @property
    def response_time(self):
        return self.time_fall + self.time_rise

    def __str__(self):
        return (
            self.product_model_type.name 
            + "@" + self.product_model_type.factory.name
            # + " Vop:" + self.voltage
        )

    def get_absolute_url(self):
        return reverse("opticals:ref_detail", kwargs={"slug": self.slug})


class ValidManager(models.Manager):
    def valided(self, **kwargs):
        return self.filter(is_valid=True, **kwargs)


class OpticalsFittingModel(TimeStampedModel):
    # TODO: to be deprecated
    experiment = models.ForeignKey(
        "products.Experiment", on_delete=models.CASCADE)
    lc = models.ForeignKey("materials.LiquidCrystal", on_delete=models.CASCADE)
    # Origin data ranges
    cell_gap_upper = models.FloatField()
    cell_gap_lower = models.FloatField()
    
    # Fitting models
    # RTs
    voltage = PickledObjectField()
    response_time = PickledObjectField()
    time_rise = PickledObjectField()
    time_fall = PickledObjectField()
    # OPTs
    w_x = PickledObjectField()
    w_y = PickledObjectField()
    w_capital_y = PickledObjectField()
    lc_percent = PickledObjectField()
    transmittance = PickledObjectField()
    v_percent = PickledObjectField()
    # collect all r2
    r2 = models.JSONField()

    # Custom model manager
    objects = ValidManager()

    # valid system
    is_valid = models.BooleanField(default=False)

    def valid(self):
        self.is_valid = True
        self.save()

    def invalid(self):
        self.is_valid = False
        self.save()

    def __str__(self):
        return f"fitting model of {self.lc.name} @ {self.experiment.name}"

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["experiment", "lc"], name="opticals_scipy_model"
            )
        ]

class OptFittingModel(TimeStampedModel):
    experiment = models.ForeignKey(
        'products.Experiment',
        on_delete=models.CASCADE,
    )
    # Configurations
    lc = models.ForeignKey(
        'materials.LiquidCrystal', 
        on_delete=models.CASCADE
    )
    pi = models.ForeignKey(
        'materials.Polyimide',
        on_delete=models.CASCADE
    )
    seal = models.ForeignKey(
        'materials.Seal',
        on_delete=models.CASCADE
    )
    
    def slug_gen(obj): # type: ignore
        exp = obj.experiment.name
        lc = obj.lc.name.replace('-','')
        pi = obj.pi.name.replace('-','')
        seal = obj.seal.name.replace('-','')
        return f'{lc}-{pi}-{seal}-{exp}'    
    
    slug = AutoSlugField(
        unique=True, always_update=False,
        populate_from=slug_gen
    ) # type: ignore
    
    # Origin data ranges
    cell_gap_upper = models.FloatField()
    cell_gap_lower = models.FloatField()
    
    # Fitting models
    # OPTs
    w_x = PickledObjectField()
    w_y = PickledObjectField()
    w_capital_y = PickledObjectField()
    lc_percent = PickledObjectField()
    transmittance = PickledObjectField()
    v_percent = PickledObjectField()
    # collect all r2
    r2 = models.JSONField()
    
    def __str__(self):
        return f"opt fitting model of {self.slug}"

class RTFittingModel(TimeStampedModel):
    experiment = models.ForeignKey(
        'products.Experiment',
        on_delete=models.CASCADE,
    )
    # Configurations
    lc = models.ForeignKey(
        'materials.LiquidCrystal', 
        on_delete=models.CASCADE
    )
    pi = models.ForeignKey(

td_toolkits_v3/templates/opticals/advanced_contrast_index.html
{% extends "base.html" %}

{% block title %}
Advanced Contrast Ratio Calculation
{% endblock title %}

{% block content %}
<h1>Advanced Contrast Ratio Calculation</h1>
<div>
    <ol>
        <li><a href="{% url 'opticals:blu_upload' %}">Upload Back Light</a></li>
        <li><a href="{% url 'materials:refraction_index_upload' %}" >Upload 5 ne, no for LC</a></li>
        <li><a href="{% url 'opticals:advanced_contrast_calculation' %}" >Calculate</a></li>
    </ol>
</div>
{% endblock content %}

td_toolkits_v3/templates/opticals/data_dump.html
{% extends "base.html" %}
{% block title %}Optical Data Dump{% endblock title %}
{% block content %}
<h2>Optical Data Dump</h2>
Tools for dumping the origin fitting data.(Preprocessed Data)
<hr>
<form action='' method='GET'>
    <label>Experiment</label>
    <select class='form-select' name='exp'>
        {% for exp in exps %}
        <option>
            {{ exp.name }}
        </option>
        {% endfor %}
    </select>
    <label>Cell Gap</label>
    <select class='form-select' name='cell_gap'>
        <option selected value='axo'>AXO</option>
        <option value='rdl'>RD-Line(1 Point)</option>
        <option value='rdl_alter'>RD-Line(6 Point)</option>
        <option value='None'>None</option>
    </select>
    <button type='submit' class='btn btn-primary'>
        Download
    </button>
</form>

<div class='alert alert-info mt-5'>
    <h5 class="alert-heading">Note:</h5>
    This is not downloading the raw data, on the other hand, 
    it's a re-order table with LC conditions and cell gaps, 
    though you should upload the conditions and AXO/RDL cell gaps data.
    If there is no cell gap data, select <strong>None</strong>
</div>

<div class='alert alert-warning'>
    <h5 class="alert-heading">Warning:</h5>
    This would download the data with thousands of rows.
    If you just want to compare TR 2 result, using
    <a href="{% url 'opticals:search' %}">Optical Search</a>
</div>



{% endblock content %}

td_toolkits_v3/templates/opticals/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Opticals{% endblock title %}

{% block content %}
<h1>Opticals</h1>
<div>
    <a href="{% url 'opticals:search' %}?profile=default" class='btn btn-primary'>
        TR2 Optical Search
    </a>
</div>
<hr>
<div>
    <h2>Tutorial</h2>
    <a class='btn btn-info' href='/wiki/optical-user-guide' target="_blank">User Guide</a>
</div>
<hr>
<div>
    <h2>Data Upload</h2>
    <ol>
        <li> <a href="{% url 'materials:upload' %}">Material Properties Upload</a> </li>
        <li> <a href="{% url 'products:chip_upload' %}">Chip Conditions Upload</a> </li>
        <li> <a href="{% url 'opticals:rdl_cell_gap_alter_upload' %}">RDL Cell Gap Upload</a> </li>
        <li> <a href="{% url 'opticals:axo_upload' %}">AXO Cell Gap Upload</a> </li>
        <li> <a href="{% url 'opticals:toc_opt_log_upload' %}">TOC VT Upload</a> </li>
        <li> <a href="{% url 'opticals:toc_rt_log_upload' %}">TOC RT Upload</a> </li>
        <li> <a href="{% url 'opticals:ref_list' %}"> Optical Reference Product Setting </a></li>
        <li> <a href="{% url 'opticals:search_profile_list' %}"> Profile Setting </a></li>
    </ol>
</div>
{% comment %} <div>
    <h2>LC TR2 Standard Process</h2>
    <ol>
        <li> Data Upload </li>
        <li> <a href="{% url 'opticals:ref_list' %}"> Ref Setting </a></li>
        <li> <a href="{% url 'opticals:calculate' %}">TR2 Optical fitting</a></li>
        <li> <a href="{% url 'opticals:search_profile_list' %}">Optical Search Profile</a></li>
    </ol>
</div> {% endcomment %}
<hr>
<div>
    <h2>TR2 Standard Process</h2>
    <ol>
        <li> Data Upload </li>
        <li> <a href="{% url 'opticals:opt_fitting' %}">TR2 OPT fitting</a></li>
        <li> <a href="{% url 'opticals:rt_fitting' %}">TR2 RT fitting</a></li>
        <li> <a href="{% url 'opticals:tr2' %}">Show Result</a></li>
        <li> <a href="{% url 'opticals:advanced_contrast' %}">Advanced Contrast Ratio</a></li>
    </ol>
</div>
<hr>
<div>
    <h2>Other Funcitons</h2>
    <ol>
        <li><a href="{% url 'opticals:data_dump' %}">OPT Data Dump</a></li>
    </ol>
</div>
{% endblock content %}

td_toolkits_v3/templates/opticals/opticalreference_detail.html
{% extends "base.html" %}
{% block title %}Opt Ref: {{ opticalreference }}{% endblock title %}
{% block content %}
<h2>{{ opticalreference }}</h2>
<table class='table table-hover text-center table-striped'>
    <thead>
        <tr>
            <th>Item</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>LC</th>
            <td>{{ opticalreference.lc }}</td>
        </tr>
        <tr>
            <th>PI</th>
            <td>{{ opticalreference.pi }}</td>
        </tr>
        <tr>
            <th>Seal</th>
            <td>{{ opticalreference.seal }}</td>
        </tr>
        <tr>
            <th>Cell Gap(um)</th>
            <td>{{ opticalreference.cell_gap }}</td>
        </tr>
        <tr>
            <th>Voltage(V)</th>
            <td>{{ opticalreference.voltage }}</td>
        </tr>
        <tr>
            <th>ITO Slit(°)</th>
            <td>{{ opticalreference.ito_slit }}</td>
        </tr>
        <tr>
            <th>TFT</th>
            <td>{{ opticalreference.get_tft_tech_display }}</td>
        </tr>
        <tr>
            <th>T%</th>
            <td>{{ opticalreference.transmittance }}</td>
        </tr>
        <tr>
            <th>Tr(ms)</th>
            <td>{{ opticalreference.time_rise }}</td>
        </tr>
        <tr>
            <th>Tf(ms)</th>
            <td>{{ opticalreference.time_fall }}</td>
        </tr>
        <tr>
            <th>RT(ms)</th>
            <td>{{ opticalreference.response_time }}</td>
        </tr>
        <tr>
            <th>G2G(ms)</th>
            <td>{{ opticalreference.gray_to_gray }}</td>
        </tr>
        <tr>
            <th>Wx</th>
            <td>{{ opticalreference.w_x }}</td>
        </tr>
        <tr>
            <th>Wy</th>
            <td>{{ opticalreference.w_y }}</td>
        </tr>
        <tr>
            <th>CR</th>
            <td>{{ opticalreference.contrast_ratio }}</td>
        </tr>
    </tbody>
</table>

<a href="{% url 'opticals:ref_update' opticalreference.slug %}" class="btn btn-info">Update</a>
{% endblock content %}

td_toolkits_v3/templates/opticals/opticalreference_list.html
{% extends "base.html" %}

{% block title %}Optical Reference List{% endblock title %}

{% block content %}
<h2>Optical Reference List</h2>
<ul>
{% for obj in opticalreference_list %}
<li><a href="{% url 'opticals:ref_detail' obj.slug %}">{{ obj }}</a></li>
{% endfor %}
</ul>
<hr/>
<p>Don't see the Reference listed here?</p>
<p>
<a class="btn btn-primary"
href="{% url 'opticals:ref_add' %}" role="button">
Add REF
</a>
</p>
{% endblock content %}

td_toolkits_v3/templates/opticals/opticalsearchprofile_detail.html
{% extends "base.html" %}
{% block title %}
Optical Search Profile: {{ opticalsearchprofile }}
{% endblock title %}
{% block content %}
<h2>Optical Search Profile: {{ opticalsearchprofile }}</h2>
<p>This profile is to constrain the search result.</p> 
<div class='table'>
<table class='table table-hover text-center table-striped'>
    <thead>
        <tr>
            <th>Item</th>
            <th>Value</th>
            <th>Weight</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Ref Product</th>
            <td>{{ opticalsearchprofile.ref_product }}</td>
            <td></td>
        </tr>
        <tr>
            <th>LC% minimum</th>
            <td>{{ opticalsearchprofile.lc_percent }}</td>
            <td>{{ opticalsearchprofile.lc_percent_weight }}</td>
        </tr>
        <tr>
            <th>RT(ms) maximum</th>
            <td>{{ opticalsearchprofile.response_time }}</td>
            <td>{{ opticalsearchprofile.response_time_weight }}</td>
        </tr>
        <tr>
            <th>ΔEab* maximum</th>
            <td>{{ opticalsearchprofile.delta_e_ab }}</td>
            <td>{{ opticalsearchprofile.delta_e_ab_weight }}</td>
        </tr>
        <tr>
            <th>CR minimum</th>
            <td>{{ opticalsearchprofile.contrast_ratio }}</td>
            <td>{{ opticalsearchprofile.contrast_ratio_weight }}</td>
        </tr>
        <tr>
            <th>Remark(Is data fitting out of range of raw?)</th>
            <td>{{ opticalsearchprofile.remark }}</td>
            <td></td>
        </tr>
    </tbody>
</table>
</div>
<a href="{% url 'opticals:search_profile_update' opticalsearchprofile.slug %}"
    class='btn btn-info'
>
    Update
</a>
{% endblock content %}

td_toolkits_v3/templates/opticals/opticalsearchprofile_list.html
{% extends "base.html" %}

{% block title %}Optical Search Profile List{% endblock title %}

{% block content %}
<h2>Optical Search Profile List</h2>
<ul>
{% for obj in opticalsearchprofile_list %}
<li><a href="{% url 'opticals:search_profile_detail' obj.slug %}">{{ obj }}</a></li>
{% endfor %}
</ul>
<hr/>
<p>Add more profile if you like.</p>
<p>
<a class="btn btn-primary"
href="{% url 'opticals:search_profile_add' %}" role="button">
Add Profile
</a>
</p>
{% endblock content %}